Name: test-project #可选 填的话在增加一个 {"project": "Name"}的filed
Level: debug  #日志等级 debug info warn error
Stacktrace: true #默认为true 在error级别及以上显示堆栈
AddCaller: true #默认为true  增加调用者信息
CallShip: 3 # 默认为3 调用栈深度
Mode: console #默认为console 输出到控制台  console file
Json: false #默认为false  是否json格式化
FileName:  #可选 file模式参数 输出到指定文件
ErrorFileName:  #可选 file模式参数 错误日志输出到的地方
MaxSize: 0 #可选 file模式参数 文件大小限制 单位MB
MaxAge: 0 #可选 file模式参数 文件最大保存时间 单位天
MaxBackup: 0 #可选 file模式参数 最大的日志数量
Async: true #默认为false file模式参数 是否异步落盘。
Compress: false #默认为false file模式参数 是否压缩
Console: false #默认为false file模式参数 是否同时输出到控制台
Color: true #默认为false  输出是否彩色 在开发的时候推荐使用。
IsReport: true  #默认为false 是否上报到im工具
ReportConfig: # 上报配置 warn级别以上报到im工具
  Type: lark # 可选 lark wx tg
  Token: https://open.larksuite.com/open-apis/bot/v2/hook/4f17830b-317b-47a7-84c7-99286195354e # lark填webhook tg填token wx填key
  ChatID: 0 # tg填chatID 其他不用填
  FlushSec: 3 #默认为3 刷新间隔单位为秒 开发测试调小一点，生产环境调大一点
  MaxCount: 20 #默认为20  最大缓存数量 达到刷新间隔或最大记录数 触发发送  开发测试调小一点，生产环境调大一点
  Level: warn
